# Alacritty - TOML configuration file format.

live_config_reload = true

import = [
  # uncomment the flavour you want below:
  "~/.config/alacritty/catppuccin-mocha.toml",
  "~/.config/alacritty/keybindings.toml"
]

[env]
  TERM = "xterm-256color"

# live_config_reload = true | false
# Live config reload (changes require restart)
# Default: true

[window]
  decorations = "None"
  # decorations = "Full"
  # decorations = "Full" | "None" | "Transparent" | "Buttonless"
  startup_mode = "Windowed"
  title = "Alacritty"
  dynamic_title = true 
  decorations_theme_variant = "None"
  opacity = 0.95
  blur = true
  dimensions = { columns = 120, lines = 40 }
  padding = { x = 4, y = 10 }

# multiplier = <integer>
# Number of line scrolled for every input scroll increment.
# Default: 3

[scrolling]
  history = 10000
  multiplier = 3

[font]
  size = 12
  # normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
  italic = { family = "SpaceMono Nerd Font", style = "Italic"}
  bold = { family = "SpaceMono Nerd Font", style = "Bold"}
  bold_italic = { family = "SpaceMono Nerd Font", style = "Bold Italic"}
  normal = { family = "SpaceMono Nerd Font", style = "Regular" }
  builtin_box_drawing = true

